name: Package Just Drop it
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Build Project
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a JustDropIt.7z "Data Files"
<<<<<<< HEAD

=======
   
>>>>>>> 9cfbddf09b82c0aca433a9e5843033cd5ba60c6a
      - name: Create Release
        uses: notlmn/release-with-changelog@v2
        with:
          header: '### Changelog'
          include-hash: true
          include-range: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: JustDropIt.7z
